// Code generated by mockery v2.43.2. DO NOT EDIT.

package enginemocks

import (
	mock "github.com/stretchr/testify/mock"
	engine "github.com/tak-sh/tak/pkg/headless/engine"
)

// Evaluator is an autogenerated mock type for the Evaluator type
type Evaluator struct {
	mock.Mock
}

type Evaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *Evaluator) EXPECT() *Evaluator_Expecter {
	return &Evaluator_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function with given fields: c, i
func (_m *Evaluator) Eval(c *engine.Context, i engine.Instruction) engine.EvalHandle {
	ret := _m.Called(c, i)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 engine.EvalHandle
	if rf, ok := ret.Get(0).(func(*engine.Context, engine.Instruction) engine.EvalHandle); ok {
		r0 = rf(c, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(engine.EvalHandle)
		}
	}

	return r0
}

// Evaluator_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type Evaluator_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - c *engine.Context
//   - i engine.Instruction
func (_e *Evaluator_Expecter) Eval(c interface{}, i interface{}) *Evaluator_Eval_Call {
	return &Evaluator_Eval_Call{Call: _e.mock.On("Eval", c, i)}
}

func (_c *Evaluator_Eval_Call) Run(run func(c *engine.Context, i engine.Instruction)) *Evaluator_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*engine.Context), args[1].(engine.Instruction))
	})
	return _c
}

func (_c *Evaluator_Eval_Call) Return(_a0 engine.EvalHandle) *Evaluator_Eval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Evaluator_Eval_Call) RunAndReturn(run func(*engine.Context, engine.Instruction) engine.EvalHandle) *Evaluator_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// EventQueue provides a mock function with given fields:
func (_m *Evaluator) EventQueue() engine.EventQueue {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventQueue")
	}

	var r0 engine.EventQueue
	if rf, ok := ret.Get(0).(func() engine.EventQueue); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(engine.EventQueue)
		}
	}

	return r0
}

// Evaluator_EventQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventQueue'
type Evaluator_EventQueue_Call struct {
	*mock.Call
}

// EventQueue is a helper method to define mock.On call
func (_e *Evaluator_Expecter) EventQueue() *Evaluator_EventQueue_Call {
	return &Evaluator_EventQueue_Call{Call: _e.mock.On("EventQueue")}
}

func (_c *Evaluator_EventQueue_Call) Run(run func()) *Evaluator_EventQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Evaluator_EventQueue_Call) Return(_a0 engine.EventQueue) *Evaluator_EventQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Evaluator_EventQueue_Call) RunAndReturn(run func() engine.EventQueue) *Evaluator_EventQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvaluator creates a new instance of Evaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Evaluator {
	mock := &Evaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
