// Code generated by mockery v2.43.2. DO NOT EDIT.

package enginemocks

import (
	mock "github.com/stretchr/testify/mock"
	engine "github.com/tak-sh/tak/pkg/headless/engine"

	time "time"
)

// Instruction is an autogenerated mock type for the Instruction type
type Instruction struct {
	mock.Mock
}

type Instruction_Expecter struct {
	mock *mock.Mock
}

func (_m *Instruction) EXPECT() *Instruction_Expecter {
	return &Instruction_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: err
func (_m *Instruction) Cancel(err error) {
	_m.Called(err)
}

// Instruction_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type Instruction_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - err error
func (_e *Instruction_Expecter) Cancel(err interface{}) *Instruction_Cancel_Call {
	return &Instruction_Cancel_Call{Call: _e.mock.On("Cancel", err)}
}

func (_c *Instruction_Cancel_Call) Run(run func(err error)) *Instruction_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *Instruction_Cancel_Call) Return() *Instruction_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *Instruction_Cancel_Call) RunAndReturn(run func(error)) *Instruction_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Eval provides a mock function with given fields: c, to
func (_m *Instruction) Eval(c *engine.Context, to time.Duration) error {
	ret := _m.Called(c, to)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*engine.Context, time.Duration) error); ok {
		r0 = rf(c, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Instruction_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type Instruction_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - c *engine.Context
//   - to time.Duration
func (_e *Instruction_Expecter) Eval(c interface{}, to interface{}) *Instruction_Eval_Call {
	return &Instruction_Eval_Call{Call: _e.mock.On("Eval", c, to)}
}

func (_c *Instruction_Eval_Call) Run(run func(c *engine.Context, to time.Duration)) *Instruction_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*engine.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *Instruction_Eval_Call) Return(_a0 error) *Instruction_Eval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Instruction_Eval_Call) RunAndReturn(run func(*engine.Context, time.Duration) error) *Instruction_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function with given fields:
func (_m *Instruction) GetId() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Instruction_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type Instruction_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *Instruction_Expecter) GetId() *Instruction_GetId_Call {
	return &Instruction_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *Instruction_GetId_Call) Run(run func()) *Instruction_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Instruction_GetId_Call) Return(_a0 string) *Instruction_GetId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Instruction_GetId_Call) RunAndReturn(run func() string) *Instruction_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *Instruction) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Instruction_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type Instruction_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *Instruction_Expecter) String() *Instruction_String_Call {
	return &Instruction_String_Call{Call: _e.mock.On("String")}
}

func (_c *Instruction_String_Call) Run(run func()) *Instruction_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Instruction_String_Call) Return(_a0 string) *Instruction_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Instruction_String_Call) RunAndReturn(run func() string) *Instruction_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewInstruction creates a new instance of Instruction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstruction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Instruction {
	mock := &Instruction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
